// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gaia-client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GaiaClient_GetSecret_FullMethodName   = "/gaia.GaiaClient/GetSecret"
	GaiaClient_ListSecrets_FullMethodName = "/gaia.GaiaClient/ListSecrets"
)

// GaiaClientClient is the client API for GaiaClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GaiaClientClient interface {
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	// New: ListSecrets returns all secrets for the authenticated client plus common when not filtered.
	ListSecrets(ctx context.Context, in *ClientListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
}

type gaiaClientClient struct {
	cc grpc.ClientConnInterface
}

func NewGaiaClientClient(cc grpc.ClientConnInterface) GaiaClientClient {
	return &gaiaClientClient{cc}
}

func (c *gaiaClientClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, GaiaClient_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gaiaClientClient) ListSecrets(ctx context.Context, in *ClientListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, GaiaClient_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GaiaClientServer is the server API for GaiaClient service.
// All implementations must embed UnimplementedGaiaClientServer
// for forward compatibility.
type GaiaClientServer interface {
	GetSecret(context.Context, *GetSecretRequest) (*Secret, error)
	// New: ListSecrets returns all secrets for the authenticated client plus common when not filtered.
	ListSecrets(context.Context, *ClientListSecretsRequest) (*ListSecretsResponse, error)
	mustEmbedUnimplementedGaiaClientServer()
}

// UnimplementedGaiaClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGaiaClientServer struct{}

func (UnimplementedGaiaClientServer) GetSecret(context.Context, *GetSecretRequest) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedGaiaClientServer) ListSecrets(context.Context, *ClientListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedGaiaClientServer) mustEmbedUnimplementedGaiaClientServer() {}
func (UnimplementedGaiaClientServer) testEmbeddedByValue()                    {}

// UnsafeGaiaClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GaiaClientServer will
// result in compilation errors.
type UnsafeGaiaClientServer interface {
	mustEmbedUnimplementedGaiaClientServer()
}

func RegisterGaiaClientServer(s grpc.ServiceRegistrar, srv GaiaClientServer) {
	// If the following call pancis, it indicates UnimplementedGaiaClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GaiaClient_ServiceDesc, srv)
}

func _GaiaClient_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaiaClientServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GaiaClient_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaiaClientServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GaiaClient_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaiaClientServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GaiaClient_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaiaClientServer).ListSecrets(ctx, req.(*ClientListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GaiaClient_ServiceDesc is the grpc.ServiceDesc for GaiaClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GaiaClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.GaiaClient",
	HandlerType: (*GaiaClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _GaiaClient_GetSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _GaiaClient_ListSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaia-client.proto",
}
