---
# Staging Inventory for Gaia Deployment

all:
  children:
    gaia_servers:
      hosts:
        gaia-staging:
          ansible_host: 192.168.1.200
          ansible_user: ubuntu
          ansible_become: true
