name: Release Gaia

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Tidy modules
        run: go mod tidy

      - name: Run cross-platform build
        run: make cross-build

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This will create a release with the same name as the tag.
          # The body of the release will be empty by default. You can add release notes here.
          files: bin/cross-build/*
